name: Run Python Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage

    - name: Запуск тестов с coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml

    - name: Отчёт о покрытии 
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
